In [ ]:
#@title Default title text
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [14]:
### To run the script simply replace the embedding data path with the path to the embedding data in your pc and run all the cells in this script. To obtain the same results pubblished make sure that the libraries listed below are the same versions as stated here
### Running time: ~ 1'
import pandas as pd
import numpy as np
import scipy
import sklearn
import sklearn.linear_model
import sklearn.ensemble

print('pandas version', pd.__version__)       # version 1.1.0 was used in the paper
print('numpy version', np.__version__)        # version 1.19.1 was used in the paper
print('scipy version', scipy.__version__)     #  version 1.4.1 was used in the paper
print('sklearn version', sklearn.__version__) # 0.23.1 was used in the paper

pandas version 1.1.0
numpy version 1.19.1
scipy version 1.4.1
sklearn version 0.23.1

In [15]:
# TODO: Change to final paths when available.
EMBEDDING_DATA_PATH = '/home/bianca/Documents/Google/PaperData/adpd_data_sources/tile_embeddings_normalized_well_mean.h5'
CELLPROFILER_DATA_PATH = '/home/bianca/Documents/Google/PaperData/adpd_data_sources/cellprofiler_features_normalized_well_mean.h5'
METADATA_PATH = '/home/bianca/Documents/Google/PaperData/Schiff et al. Supplementary Tables.xlsx'

In [16]:
embedding_df = pd.read_hdf(EMBEDDING_DATA_PATH)
embedding_df

,,,,,0,1,2,3,4,5,6,7,8,9,...,310,311,312,313,314,315,316,317,318,319
batch,plateset,plate,well,cell_line_id,,,,,,,,,,,,,,,,,,,,,
1,0,01,A01,35,-0.003832,-0.053635,-0.031690,-0.006442,-0.005141,-0.024213,0.018144,-0.055491,-0.035721,-0.005130,...,-0.011497,0.017889,-0.021675,0.022078,-0.017706,0.020405,-0.014038,0.009244,-0.012189,0.016143
2,0,01,A01,35,0.022274,-0.056484,-0.035250,-0.005860,-0.016999,-0.049781,0.026826,-0.067544,-0.028236,-0.005333,...,-0.016035,0.005888,-0.024372,0.014015,-0.010143,0.027827,0.001345,0.004838,0.015076,0.022774
3,0,01,A01,35,0.015161,-0.012027,-0.021590,0.001127,-0.006178,-0.014007,0.022263,-0.019491,-0.003813,0.003873,...,-0.012009,0.005477,-0.011697,-0.004516,0.005495,0.017369,-0.005781,0.000433,-0.004532,0.003598
4,0,01,A01,35,0.018679,-0.026285,-0.017298,0.001287,-0.003649,-0.019481,0.020877,-0.028387,-0.012642,-0.000196,...,-0.009035,-0.002165,-0.008494,-0.015720,-0.000454,0.018913,-0.016147,0.004312,-0.001212,-0.002965
1,0,02,A01,35,-0.002364,-0.045927,-0.011868,-0.010643,-0.012125,-0.019325,0.008511,-0.054144,-0.012824,0.014084,...,0.001100,0.022379,-0.024466,-0.000028,-0.008784,0.022262,-0.027353,-0.028354,0.007130,0.014048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1,11,H12,13,-0.004940,-0.029381,0.004020,-0.008192,0.003275,-0.012327,0.008811,-0.048467,-0.022490,0.017067,...,-0.033368,0.033175,-0.001780,0.011340,-0.005872,0.003335,0.002404,0.023151,0.007643,0.023990
1,1,12,H12,13,-0.005450,-0.018399,0.001500,-0.019553,-0.004166,-0.020499,-0.002498,-0.041059,-0.018681,0.004016,...,-0.028354,0.032691,-0.004281,0.012742,-0.011195,0.017663,0.017207,0.026779,-0.005766,0.020175
2,1,12,H12,13,-0.009530,-0.009070,0.004975,-0.002393,0.004096,-0.008867,0.006656,0.002096,0.001669,0.002088,...,-0.013985,0.043906,0.018870,0.003000,-0.014602,0.009916,0.029535,0.029526,-0.012254,-0.003028
3,1,12,H12,13,-0.010722,-0.082936,-0.028507,-0.046351,-0.017893,-0.055009,-0.010662,-0.133265,-0.034162,0.019079,...,0.022348,0.059153,-0.051811,0.056755,-0.077886,0.026159,0.003000,0.035577,0.019984,0.073564
4,1,12,H12,13,-0.010359,-0.044488,0.002807,-0.013388,-0.000038,-0.020769,0.004471,-0.053527,-0.034339,0.012224,...,-0.014866,0.039332,-0.019766,0.017830,-0.016718,0.001632,0.013883,0.036781,-0.011726,0.006372

In [17]:
CellProfiler_df = pd.read_hdf(CELLPROFILER_DATA_PATH)
CellProfiler_df

,,,,,cells_AreaShape_Area,cells_AreaShape_Center_X,cells_AreaShape_Center_Y,cells_AreaShape_Center_Z,cells_AreaShape_Compactness,cells_AreaShape_Eccentricity,cells_AreaShape_EulerNumber,cells_AreaShape_Extent,cells_AreaShape_FormFactor,cells_AreaShape_MajorAxisLength,...,nuclei_Texture_Variance_RNA_10_02,nuclei_Texture_Variance_RNA_10_03,nuclei_Texture_Variance_RNA_3_00,nuclei_Texture_Variance_RNA_3_01,nuclei_Texture_Variance_RNA_3_02,nuclei_Texture_Variance_RNA_3_03,nuclei_Texture_Variance_RNA_5_00,nuclei_Texture_Variance_RNA_5_01,nuclei_Texture_Variance_RNA_5_02,nuclei_Texture_Variance_RNA_5_03
batch,plateset,plate,well,cell_line_id,,,,,,,,,,,,,,,,,,,,,
1,0,01,B03,95,-0.014402,-0.006589,0.005971,0.0,-0.014558,-0.008185,-0.012663,0.017386,0.022379,-0.018125,...,-0.006587,-0.006605,-0.006648,-0.006618,-0.006640,-0.006641,-0.006637,-0.006589,-0.006622,-0.006629
2,0,01,B03,95,-0.018674,0.005994,-0.012132,0.0,-0.019783,-0.013436,-0.009278,0.025610,0.034168,-0.024928,...,0.000212,0.000185,0.000234,0.000234,0.000245,0.000218,0.000214,0.000220,0.000225,0.000203
3,0,01,B03,95,-0.022017,-0.001533,-0.010276,0.0,-0.021137,-0.020005,0.003761,0.023600,0.038103,-0.029954,...,-0.000450,-0.000458,-0.000417,-0.000428,-0.000411,-0.000436,-0.000441,-0.000445,-0.000437,-0.000457
4,0,01,B03,95,-0.005963,-0.001369,0.000310,0.0,-0.018417,-0.028806,-0.027224,0.026765,0.021630,-0.013929,...,-0.000586,-0.000545,-0.000597,-0.000603,-0.000596,-0.000593,-0.000601,-0.000604,-0.000598,-0.000589
1,0,02,B03,95,-0.014201,0.032121,-0.029059,0.0,-0.026708,-0.013273,-0.016803,0.037246,0.043757,-0.023713,...,0.005217,0.005060,0.005421,0.005394,0.005403,0.005387,0.005389,0.005330,0.005363,0.005316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0,05,E07,20,0.000836,0.005088,0.016994,0.0,-0.001352,0.001683,0.009896,0.001927,-0.006940,0.001420,...,0.000135,0.000164,0.000118,0.000116,0.000121,0.000120,0.000117,0.000116,0.000120,0.000120
1,0,06,E07,20,0.000238,0.013216,-0.017320,0.0,0.007510,0.009410,0.010039,-0.007737,-0.004583,0.005370,...,-0.000636,-0.000516,-0.000766,-0.000749,-0.000762,-0.000746,-0.000739,-0.000706,-0.000736,-0.000696
2,0,06,E07,20,0.006441,0.010526,0.002617,0.0,0.012494,0.009188,-0.000603,-0.014989,-0.013782,0.012495,...,-0.009205,-0.009031,-0.009274,-0.009289,-0.009278,-0.009246,-0.009264,-0.009272,-0.009270,-0.009207
3,0,06,E07,20,0.003510,0.004951,-0.019528,0.0,0.010659,0.009178,0.009298,-0.012873,-0.002498,0.008940,...,0.006283,0.006325,0.006182,0.006211,0.006193,0.006193,0.006197,0.006252,0.006214,0.006216
4,0,06,E07,20,-0.000171,0.004454,0.009320,0.0,0.001602,0.008318,0.019769,-0.005036,-0.009535,0.001601,...,-0.002551,-0.002499,-0.002529,-0.002545,-0.002521,-0.002528,-0.002549,-0.002571,-0.002538,-0.002545

In [18]:
all_metadata_df = pd.read_excel(METADATA_PATH)
all_metadata_df

,Cell line ID,Donor ID,Cross-val fold,Pair ID,Disease state,Sex,Age,European ancestry,UPDRS score,Biopsy collection year,Biopsy location,Thaw format,Thaw freeze date,Doubling time
0,01,50121,1.0,0.0,Healthy,F,54,0.99,,2012,unspecified,6w,2019-06-17,3.316818
1,02,51255,1.0,0.0,LRRK2 PD,F,56,0.92,71,2017,left upper thigh,6w,2019-06-17,2.656416
2,03,51260,2.0,1.0,Healthy,F,64,0.98,,2017,left upper leg,12w→6w,2019-08-09,2.704582
3,04,51253,2.0,1.0,Sporadic PD,F,63,0.99,23,2017,left upper arm,6w,2019-07-30,3.411927
4,05,50114,4.0,2.0,Healthy,M,67,0.94,,2012,unspecified,6w,2019-07-31,2.773009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,51239,NaN,NaN,Healthy,M,67,0.99,,2019,right arm,6w,2019-07-31,2.329057
92,93,51093,NaN,NaN,Healthy,F,77,0.99,,2019,left arm,6w,2019-06-19,3.080005
93,94,51148,NaN,NaN,Healthy,M,65,0.90,,2019,upper arm,6w,2019-08-13,2.210402
94,95,50492,NaN,NaN,LRRK2 PD,M,51,0.91,,2019,left upper arm,6w,2019-07-18,3.553737
95,96,50626,NaN,NaN,Sporadic PD,M,70,0.97,43,2013,unspecified,6w,2019-09-03,2.595911

In [19]:
def clean_up_relevant_metadata(all_metadata_df):
  """Make a clean version of the relevant metadata columns we need to join with the embedding dataframe."""
  # Select the columns from the metadata that we want to merge in with the embeddings.
  metadata_to_merge_df = all_metadata_df[['Cell line ID', 'Cross-val fold', 'Disease state']].copy()

  # Rename the columns.
  metadata_to_merge_df.columns = ['cell_line_id', 'group', 'disease_state']

  # Make the disease state uppercase.
  metadata_to_merge_df['disease_state'] = metadata_to_merge_df['disease_state'].str.upper()

  # Fix the naming of the disease_state.
  metadata_to_merge_df['disease_state'].replace('SPORADIC PD', 'SPORADIC', inplace=True)
  metadata_to_merge_df['disease_state'].replace('LRRK2 PD','LRRK2', inplace=True)
  metadata_to_merge_df['disease_state'].replace('HEALTHY*','HEALTHY', inplace=True)  # May not be healthy. See paper for details.

  # Strip off the whitespace on the cell line id.
  metadata_to_merge_df.loc[:, 'cell_line_id'] = metadata_to_merge_df['cell_line_id'].str.strip()

  # Remove the * from some of the cell_line_id so we can join.
  metadata_to_merge_df['cell_line_id'].replace('48*', '48', inplace=True)
  metadata_to_merge_df['cell_line_id'].replace('57*', '57', inplace=True)

  # Drop any rows that do not have a cross validation group set. This drops all the GBA lines.
  metadata_to_merge_df.dropna(axis=0, subset=['group'], inplace=True)

  # Make cross validation group an int.
  metadata_to_merge_df['group'] = metadata_to_merge_df['group'].astype(int)

  return metadata_to_merge_df

metadata_to_merge_df = clean_up_relevant_metadata(all_metadata_df)
metadata_to_merge_df

   cell_line_id  group disease_state
0            01      1       HEALTHY
1            02      1         LRRK2
2            03      2       HEALTHY
3            04      2      SPORADIC
4            05      4       HEALTHY
..          ...    ...           ...
85           86      3      SPORADIC
86           87      3       HEALTHY
87           88      3      SPORADIC
88           89      2       HEALTHY
89           90      2      SPORADIC

[74 rows x 3 columns]

In [36]:
def merge_metadata_with_data_df(df, metadata_to_merge_df):
  """Join the metadata with the embedding dataframe."""
  # Reset the index of the dataframe before merge.
  to_merge_df = df.reset_index()

  # Merge the embedding data with the metadata.
  merged_df = pd.merge(metadata_to_merge_df, to_merge_df, on='cell_line_id')

  return merged_df
# insert either embedding_df or Cell_profiler_df 
train_test_df = merge_metadata_with_data_df(embedding_df, metadata_to_merge_df)
train_test_df

,cell_line_id,group,disease_state,batch,plateset,plate,well,0,1,2,...,310,311,312,313,314,315,316,317,318,319
0,01,1,HEALTHY,1,1,07,D03,0.004184,0.040249,0.026530,...,-0.015100,-0.017746,0.045604,-0.016558,0.040380,0.000401,0.000483,-0.017317,-0.019437,-0.026159
1,01,1,HEALTHY,2,1,07,D03,0.004639,0.020272,0.018574,...,-0.009795,0.004587,0.049970,-0.020397,0.016456,-0.014867,-0.005192,-0.006122,-0.021637,-0.039839
2,01,1,HEALTHY,3,1,07,D03,0.012636,0.029946,0.016748,...,-0.021145,-0.009695,0.050091,-0.000340,0.016756,-0.011345,-0.000120,-0.011953,-0.023764,-0.029296
3,01,1,HEALTHY,4,1,07,D03,0.008200,0.013857,0.012598,...,-0.026685,0.004242,0.031001,0.001708,0.006971,0.004401,0.014787,-0.013059,-0.025400,-0.022717
4,01,1,HEALTHY,1,1,08,D03,0.002618,0.030171,0.027768,...,-0.004445,-0.015143,0.045930,-0.024526,0.041045,-0.015062,0.004498,-0.007361,-0.022869,-0.049547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3529,90,2,SPORADIC,1,1,11,E03,0.015173,0.014493,-0.002184,...,-0.008282,-0.030635,0.015056,-0.021353,0.036720,0.002607,-0.011756,-0.035307,-0.001649,-0.016294
3530,90,2,SPORADIC,3,1,11,E03,0.006690,-0.010136,-0.000080,...,0.022990,-0.010417,-0.019210,-0.038663,0.021145,0.026774,-0.019745,-0.020217,0.007407,0.001976
3531,90,2,SPORADIC,4,1,11,E03,-0.001238,-0.085635,-0.029494,...,0.005093,0.048951,0.002258,0.052432,-0.049021,0.008997,-0.001029,0.031468,0.009586,0.057692
3532,90,2,SPORADIC,1,1,12,E03,-0.000022,-0.045230,-0.024410,...,0.001309,0.017465,-0.013068,0.012519,-0.025893,0.027894,-0.002240,-0.002403,0.009480,0.014004
3533,90,2,SPORADIC,3,1,12,E03,0.024751,-0.030504,-0.021085,...,0.002555,-0.015832,0.013252,-0.016411,0.029342,0.001236,-0.031953,-0.023168,0.005218,0.015303

In [49]:
def get_train_test_split(data,fold):
  auxTrain = data.loc[data.group != fold]
  aux_test = data.loc[data.group == fold]
  auxTrain = auxTrain.sort_values(axis=0, by=['batch', 'plate', 'well'])
  X_train = auxTrain.iloc[:,7:]
  Targ = auxTrain.disease_state
  Targ = Targ.replace('HEALTHY', 0)
  Targ = Targ.replace('SPORADIC', 1)
  y_train = Targ.replace('LRRK2', 1)

  aux_test = aux_test.sort_values(axis=0, by=['batch', 'plate', 'well'])
  X_test = aux_test.iloc[:,7:]
  Targ = aux_test.disease_state
  Targ = Targ.replace('HEALTHY', 0) 
  Targ = Targ.replace('SPORADIC', 1)
  y_test = Targ.replace('LRRK2', 1)
     
  return X_train, X_test, y_train, y_test, aux_test

def get_predictions(model_name,X_train, y_train,X_test):
  if model_name == 'LogisticCV':
    model = sklearn.linear_model.LogisticRegressionCV(
      solver='lbfgs', max_iter=1000000)
  elif model_name == 'Logistic':
    model = sklearn.linear_model.LogisticRegression(solver='lbfgs')
  elif model_name == 'RidgeCV':
    model = sklearn.linear_model.RidgeCV()
  else:
    raise ValueError('Unknown model_name: %s' % model_name)

  model.fit(X_train, y_train)
  model_predictions = model.predict(X_test)
  if model_name == 'RidgeCV':
    preds = model.predict(X_test)
  else:
    preds=model.predict_proba(X_test)[:, 1]
    
  return preds,model_predictions

def get_Cell_level_accuracy(preds):
  predictions=pd.DataFrame(preds,index = y_test.values)        
  predictions['cell_line_id'] = predictions.index
  preds3=predictions.groupby('cell_line_id').mean()
  rank_df = preds3.rank(axis = 1)
  top_prediction_df = rank_df.idxmax(axis=1)#.reset_index('cell_line_id')
  top_prediction_df = top_prediction_df+1
  top_prediction_df.astype(int)
  return np.sum(top_prediction_df.index.astype(int) == top_prediction_df)/ top_prediction_df.shape[0]

def run_prediction_model(data, model_name):
  """Train the model and return the prediction results."""
  Results = pd.DataFrame(
      columns=['group0', 'group1', 'group2', 'group3', 'group4', 'mean', 'std'])

  for fold in np.unique(data.group):
    
    
    X_train, X_test, y_train,y_test, aux_test = get_train_test_split(data,fold)
    
    preds,model_predictions=get_predictions(model_name,X_train, y_train,X_test)
    
    pred_df = pd.DataFrame(data=preds, index=X_test.index, columns=['pred'])
    pred_df['cell_line_id'] = aux_test.cell_line_id
    pred_arr = pred_df.groupby('cell_line_id').mean()
    pred_df['disease_state'] = aux_test.disease_state
    pred_arr = pred_df.groupby(['cell_line_id', 'disease_state']).mean()
    pred_arr = pred_arr.reset_index()
    pred_arr['true'] = 0
    for line in pred_arr.cell_line_id:
      if aux_test.loc[aux_test.cell_line_id == line,
                      'disease_state'].values[0] != 'HEALTHY':
        pred_arr.loc[pred_arr.cell_line_id == line, 'true'] = 1
    Results.loc[
        'sporadic_AUC', 'group' + str(int(fold))] = sklearn.metrics.roc_auc_score(
            pred_arr.drop(
                pred_arr.loc[pred_arr.disease_state == 'LRRK2'].index).true,
            pred_arr.drop(
                pred_arr.loc[pred_arr.disease_state == 'LRRK2'].index).pred)
    Results.loc[
        'LRRK2_AUC', 'group' + str(int(fold))] = sklearn.metrics.roc_auc_score(
            pred_arr.drop(
                pred_arr.loc[pred_arr.disease_state == 'SPORADIC'].index).true,
            pred_arr.drop(
                pred_arr.loc[pred_arr.disease_state == 'SPORADIC'].index).pred)
    Results.loc['total_AUC',
                'group' + str(int(fold))] = sklearn.metrics.roc_auc_score(
                    pred_arr.true, pred_arr.pred)

  Results.loc['sporadic_AUC', 'mean'] = np.mean(Results.loc['sporadic_AUC'].values[0:-2])
  Results.loc['sporadic_AUC', 'std'] = np.std(Results.loc['sporadic_AUC'].values[0:-2])
  Results.loc['LRRK2_AUC', 'mean'] = np.mean(Results.loc['LRRK2_AUC'].values[0:-2])
  Results.loc['LRRK2_AUC', 'std'] = np.std(Results.loc['LRRK2_AUC'].values[0:-2])

  Results.loc['total_AUC',
              'mean'] = np.mean(Results.loc['total_AUC'].values[0:-2])
  Results.loc['total_AUC', 'std'] = np.std(Results.loc['total_AUC'].values[0:-2])
  return Results

In [50]:
logistic_cv_result = run_prediction_model(train_test_df,'LogisticCV')
logistic_cv_result

,group0,group1,group2,group3,group4,mean,std
sporadic_AUC,0.785714,0.942857,0.690476,0.666667,0.785714,0.774286,0.0972455
LRRK2_AUC,0.75,0.857143,0.857143,1,1,0.892857,0.0958315
total_AUC,0.78125,0.918367,0.714286,0.714286,0.8125,0.788138,0.0755102

In [51]:
paper_result_df = pd.DataFrame(columns=['mean','std'])
paper_result_df.loc['sporadic_AUC','mean'] = 0.77
paper_result_df.loc['sporadic_AUC','std'] = 0.10
paper_result_df.loc['LRRK2_AUC','mean'] = 0.89
paper_result_df.loc['LRRK2_AUC','std'] = 0.10
paper_result_df.loc['total_AUC','mean'] = 0.79
paper_result_df.loc['total_AUC','std'] = 0.08
paper_result_df

              mean   std
sporadic_AUC  0.77   0.1
LRRK2_AUC     0.89   0.1
total_AUC     0.79  0.08

In [52]:
#Raises an error if the results don't match the results stated in the paper for the embedding dataframe
pd.testing.assert_frame_equal(logistic_cv_result[['mean', 'std']], paper_result_df, atol=1e-2)